export default {
  GET_MENU_LIST: 'GET_MENU_LIST', // 获取菜单列表
  CHANGE_OPENKEYS: 'CHANGE_OPENKEYS', // 菜单默认打开选项
  START_LOGIN: 'START_LOGIN', // 开始登录
  LOGIN_SUCCESS: 'LOGIN_SUCCESS', // 登录成功
  LOGINZ_FAILED: 'LOGINZ_FAILED', // 成功失败
  REGISTER_SUCCESS: 'REGISTER_SUCCESS', // 注册成功
  REGISTER_FAILED: 'REGISTER_FAILED', // 注册失败
  GET_ARTICLE_LIST: 'GET_ARTICLE_LIST', // 获取文章列表
  SWITCH_MENU: 'SWITCH_MENU', // 用于全局面包屑，待开发。。。
  ADD_CATEGORY_CUSSESS: 'ADD_CATEGORY_CUSSESS' // 获取分类列表
};
